### ISSUE TITLE
WakaTime support request

### ISSUE THREAD

**Issue by dupeiran001** [zed-industries/extensions#497]
### Check for existing issues

- [X] Completed

### Describe the feature

[WakaTime](https://wakatime.com/) is a plugin to static coding time of all IDEs together in a dashboard

I'm not sure whether it's possible to support it in zed?

Or support third party plugins?

**Comment by alanhamlett** [comment]
A minimal extension API was added in #5269, but unfortunately it only supports themes and language extensions so it's not yet possible to build an extension like WakaTime. I've opened an issue to request a full extension API similar to other IDEs:

#10795

**Comment by ewen-lbh** [comment]
I'm wondering if a wakatime "LSP" could work, it'd send requests to the server that would run the wakatime-cli.

[The documentation](https://wakatime.com/help/creating-plugin#plugin-init) on creating editor client plugins mentions running the cli:

- on init: corresponds to [`initialized`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized)
- on file focus change: [ `didOpenTextDocument`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen) seems to match
- on file content change: [`didChangeTextDocument`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) seems to match
- on file save: [`didSaveTextDocument`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didSave)

So yeah it seems doable, and would even allow easily creating editor plugins for wakatime through LSP, I may start working on this if no one already is '^^

**Comment by ewen-lbh** [comment]
Ok I did create https://github.com/ewen-lbh/wakalsp, I'll try to get sth working by the end of the week

**Comment by ewen-lbh** [comment]
Welp, I should've searched before starting a repo lmao, seems like there's already exactly this: https://github.com/mrnossiom/wakatime-lsp

**Comment by guilhermeabel** [comment]
I'm gonna try and test this out @ewen-lbh as soon as I can. Nice find

**Comment by ewen-lbh** [comment]
I started a repo for the zed extension, but i'm waiting on mrnossion/wakatime-lsp#2 

see https://github.com/ewen-lbh/zed-wakatime

**Comment by guilhermeabel** [comment]
Great!

**Comment by ewen-lbh** [comment]
I can't really test this on my setup, the file picker dialog never opens so i can't load a dev extension... imma go to sleep anyways it's past 2am in my tz lmao

**Comment by ewen-lbh** [comment]
![image](https://github.com/zed-industries/extensions/assets/39094199/2037a8c5-8599-4989-90e7-bf7560892c96)

I have a working PoC! Install instructions on the readme

**Comment by Rithvik-padma** [comment]
> ![image](https://private-user-images.githubusercontent.com/39094199/346887798-2037a8c5-8599-4989-90e7-bf7560892c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODIwMjksIm5iZiI6MTcyMDk4MTcyOSwicGF0aCI6Ii8zOTA5NDE5OS8zNDY4ODc3OTgtMjAzN2E4YzUtODU5OS00OTg5LTkwZTctYmY3NTYwODkyYzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE4Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYzMwYTBjMDg3YTRhMWM2ZWRhYzZmZDg1MmQ0MWU0YTkxYTE5MTg2NGZhM2Y0N2VkY2IyNGVmYjc2ZGI2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pG9UP4sHhfuEbHDdR9WmCeR_Tm-i9yHkXM2BcBCeHTQ)
> 
> I have a working PoC! Install instructions on the readme

I tried your method but it did not work, I was able to install it as a dev extension but coding time is not getting tracked on my dashboard
Btw I am using Linux (fedora)

**Comment by ewen-lbh** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39094199/346887798-2037a8c5-8599-4989-90e7-bf7560892c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5ODIwMjksIm5iZiI6MTcyMDk4MTcyOSwicGF0aCI6Ii8zOTA5NDE5OS8zNDY4ODc3OTgtMjAzN2E4YzUtODU5OS00OTg5LTkwZTctYmY3NTYwODkyYzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE4Mjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYzMwYTBjMDg3YTRhMWM2ZWRhYzZmZDg1MmQ0MWU0YTkxYTE5MTg2NGZhM2Y0N2VkY2IyNGVmYjc2ZGI2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pG9UP4sHhfuEbHDdR9WmCeR_Tm-i9yHkXM2BcBCeHTQ)
> > 
> > I have a working PoC! Install instructions on the readme
> 
> I tried your method but it did not work, I was able to install it as a dev extension but coding time is not getting tracked on my dashboard
> Btw I am using Linux (fedora)
> 
> 
> 
> 
> 
> 
> 
> 
> 

Ooops ._.
Please make an issue on the repo ;)

**Comment by bestgopher** [comment]
Hi, I published a plugin for wakatime. Please take a try. #1327

**Comment by bestgopher** [comment]
> A minimal extension API was added in [zed-industries/zed#5269](https://github.com/zed-industries/zed/issues/5269), but unfortunately it only supports themes and language extensions so it's not yet possible to build an extension like WakaTime. I've opened an issue to request a full extension API similar to other IDEs:
> 
> [zed-industries/zed#10795](https://github.com/zed-industries/zed/issues/10795)

Hi, here is my repo: https://github.com/bestgopher/wakatime-zed
It works find to me:
<img width="852" alt="image" src="https://github.com/user-attachments/assets/0d62bccf-86c6-4c5e-8efe-696802bd37f7">

**Comment by berkus** [comment]
@ewen-lbh is this (variation of) your code that has been published? I'm on the phone but still see way too many similarities.

**Comment by bestgopher** [comment]
@berkus You mean my code is similar with @ewen-lbh 's ? I can responsibly tell you that they have no relation whatsoever. My inspiration came from [code-stats](https://github.com/maxdeviant/zed-code-stats). Before I completed this plugin, I was not aware of the existence of this issue.

**Comment by berkus** [comment]
Okay then, just asking.

**Comment by bestgopher** [comment]
> Okay then, just asking.

Okay

**Comment by alanhamlett** [comment]
Also the desktop app can track Zed usage, but not detect project only app usage:
https://wakatime.com/desktop

**Comment by bestgopher** [comment]
> Also the desktop app can track Zed usage, but not detect project only app usage:

Hi, @alanhamlett .I recently recommended my plugin to you via email, but you didn’t reply. I’m not sure if you didn’t receive the email, but I’d still like to hear your thoughts.

**Comment by alanhamlett** [comment]
Nice work both of you! I would like to merge the two into one repo under the [WakaTime GitHub Org](https://github.com/wakatime) then give both of you write permission on the repo. First, we should decide what's best... bundling the LSP like @bestgopher or using the external [wakatime-lsp](https://github.com/mrnossiom/wakatime-lsp) like @ewen-lbh. I haven't fully read the whole source code of each plugin yet, are there any other differences?

**Comment by bestgopher** [comment]
> First, we should decide what's best... bundling the LSP like @bestgopher or using the external [wakatime-lsp](https://github.com/mrnossiom/wakatime-lsp) like @ewen-lbh

I don't known which is the best, but for me, I could maintain them by myself. In my opinion, lsp is the part of plugin, it's better to bund them in one repo.

**Comment by alanhamlett** [comment]
Yes bundling is less error-prone because there's no [extra network requests](https://github.com/ewen-lbh/zed-wakatime/blob/1f92fcc5c7cd0be3da31999698133bcccd4c9d6e/src/wakatime.rs#L75). @bestgopher can you use [the official instructions](https://wakatime.com/help/creating-plugin#releasing:distribution) for transferring the repo to `alanhamlett` GitHub username (because orgs can't receive repos) then I'll transfer it to the WakaTime GitHub org, add you and @ewen-lbh as maintainers, and make it an official plugin on the website.

**Comment by bestgopher** [comment]
> @bestgopher can you use [the official instructions](https://wakatime.com/help/creating-plugin#releasing:distribution) for transferring the repo to `alanhamlett` GitHub username

Done!

**Comment by bestgopher** [comment]
> Is that required?

The Zed extension consists of some WASM files, responsible for providing the startup commands and other initialization tasks for the language server. Currently, there are no other mechanisms for writing Zed extensions. If Zed's extension system is updated in the future, I will synchronize and update the related features accordingly.

**Comment by bestgopher** [comment]
> Is that required?

The Zed extension consists of some WASM files, responsible for providing the startup commands and other initialization tasks for the language server. Currently, there are no other mechanisms for writing Zed extensions. If Zed's extension system is updated in the future, I will synchronize and update the related features accordingly.

**Comment by alanhamlett** [comment]
So let's re-use the LSP instead of re-writing it, same as @ewen-lbh

**Comment by bestgopher** [comment]
> So let's re-use the LSP instead of re-writing it, same as @ewen-lbh

I don't understand why there is a need to dwell on this. Before developing this plugin, I was not aware of the existence of the wakatime-lsp repository. I briefly looked at its code; its functionality is quite simple and doesn't implement requirements like [rate limiting](https://wakatime.com/help/creating-plugin#sending-file-to-wakatime-cli:deciding-to-send-file-or-not) as mentioned in the Wakatime documentation. Furthermore, I don't know if this repository is still being maintained or if it might be deleted in the future. I believe the best solution would be for Wakatime to officially provide a language server. For example, they could develop a wakatime-cli lsp subcommand based on the wakatime-cli tool, which would allow extensions to be developed directly on top of it.

**Comment by alanhamlett** [comment]
Yes an official wakatime-cli-lsp is the best solution, but in general code reuse means all users get benefits of bugs or improvements instead of having to copy those changes into multiple LSP repos.

**Comment by ewen-lbh** [comment]
Hi all!

First of all, thanks @alanhamlett for the invitation! I'm honored to be named maintainer on a wakatime repo ^^

Then, to clarify things, I don't mind at all the fact that someone else made another repo that does the same thing as mine. I mean this is bound to happen at some point (and I actually [did the same](github.com/ewen-lbh/wakalsp) before discovering @mrnossiom's [wakatime-lsp](https://github.com/mrnossiom/wakatime-lsp)). I also was pretty busy with other projects and didn't have the time to ask Wakatime for an official repo transfer as the project was not completely finished (it was more of a PoC)

I also think that distributing a common wakatime-lsp would be nice, It'd lower the barrier to entry significantly for wakatime plugin creation, as LSP is really becoming a popular standard that most code editors support nowadays. (I'd even go as far as to say that most wakatime plugins should be rewritten to use a common lsp base, that would be bundled with the cli as @bestgopher mentions, but that's a lot of work for no end-user impact haha)

There's still an issue with (ab)using the LSP standard: since it's made for language support, client extensions often declare a fixed list of languages that should activate the language server. This results in a maintenance burden on client extension implementors for wakatime: they have to maintain a list of [all programming languages the editor supports](https://github.com/wakatime/zed-wakatime/blob/master/extension.toml#L11-L61), and as new ones inevitably get added, wakatime is bound to break and not report code stats for a less popular language. This is more of a Zed issue though.

Also @mrnossiom has mentionned buidling wakatime-lsp for Helix initially, maybe the IDE could also receive a repo on the wakatime org? (idk where the plugin is in term of stability)

**Comment by alanhamlett** [comment]
> Also @mrnossiom has mentionned buidling wakatime-lsp for Helix initially, maybe the IDE could also receive a repo on the wakatime org? (idk where the plugin is in term of stability)

For visibility, I've reached out to @mrnossiom about that in [this comment](https://github.com/mrnossiom/wakatime-lsp/issues/2#issuecomment-2360611441)

**Comment by mrnossiom** [comment]
Hi Alan, Ewen and `bestgopher`,

I'd be glad to transfer the repository to the `wakatime/*` namespace, where it would get more visibility. I have recently not been active on the repository because it works fine as is, but I would be happy to resolve bugs or discuss new features if necessary.

About abusing the LSP standard, I really think the LSP specification has grown enough to become more of a code editor plugin standard. I think IDEs would be kin to enable global LSPs (here's Helix tracking issue https://github.com/helix-editor/helix/pull/9318).
Aside, I've been experimenting another case of LSP abusing for spellchecking (https://github.com/mrnossiom/lspelling)

For extensions in general (and Zed's specifically), using `wakatime-lsp` as a base is quite good to bootstrap. Maybe it will later evolve into its own program to take advantage of Zed's specific API (like the VS Code extension).

To answer `bestgopher` concerns on features, my initial idea for `wakatime-lsp` was to create a thin wrapper around `wakatime-cli` which actually does most of the network, debounce, heartbeat stuff. It stores heartbeats when offline to send them all when reconnecting. I don't have to rewrite this code which is used by all, and I get to benefit from it.
Furthermore, I had written down some feature ideas as comments in my code, but I actually think these should be discussed at the CLI level to keep all the features at the same place.

Last, about https://github.com/mrnossiom/wakatime-lsp/pull/5, after having a friend installing the Zed plugin, I understand that the experience is unclear. I intend to finish Ewen's automatic `wakatime-cli` downloading. I'll add a flag to disable it for declarative systems.

Tell me Alan when do you want to proceed to transfer the repository

Hope I've answered everyone questions 😄

**Comment by mrnossiom** [comment]
If Alan prefers to bundle the LSP in the official CLI, it's an option too. The LSP implementation is far from long. I don't know if the added binary weight is visible.

**Comment by Psalmuel01** [comment]
hey all, welldone. i noticed i can view the time spent on wakatime's dashboard, but i can't seem to see it anywhere like below in the zed editor. is that possible currently?
